[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["A","B","C","D","E","F","G","I","N","T","W"]  # Specify list of error codes to report.
exclude = [
    ".tox",
    ".git",
    "__pycache__",
    "build",
    "dist",
    "proto/*",
    "*.pyc",
    "*.egg-info",
    ".cache",
    ".eggs",
]
ignore = [
    "A002",  # Argument shadowing a Python builtin.
    "A003",  # Class attribute shadowing a Python builtin.
    "D107",  # Do not require docstrings for __init__.
    "E266",  # Do not require block comments to only have a single leading #.
    "E731",  # Do not assign a lambda expression, use a def.
    "B017",  # assertRaises(Exception): or pytest.raises(Exception) should be considered evil.
    "E203",  # black and flake8 disagree on whitespace before ':'.

    "D211",  # No blank lines allowed before class docstring.
    "D213",  # Multi-line docstring summary should start at the second line.

    # TEMP
    "D100",  # Missing docstring in public module.
    "D101",  # Missing docstring in public class.
    "D102",  # Missing docstring in public method.
    "D103",  # Missing docstring in public function.
    "D104",  # Missing docstring in public package.
    "D105",  # Missing docstring in magic method.
    "D400",  # First line should end with a period.
    "D401",  # First line should be in imperative mood.
    "D404",  # First word of the first line should not be "This".
    "D417",  # Missing argument descriptions in the docstring.
    "D415",  # First line should end with a period, question mark, or exclamation point.
    "T201",  # Print found?
    "N803",  # Argument name should be lowercase.
    "N806",  # Variable in function should be lowercase.

]
mccabe.max-complexity = 11

[tool.ruff.format]
quote-style = "double"

