system_name: iddpg+bc
seed: 42
wandb_project: og-marl
training_steps: 3e5

task:
  env: mpe_omar
  scenario: simple_spread
  dataset: e

replay:
  sequence_length: 5
  sample_period: 1

system:
  linear_layer_dim: 64
  recurrent_layer_dim: 64
  discount: 0.99
  target_update_rate: 0.005
  critic_learning_rate: 3e-4
  policy_learning_rate: 3e-4
  add_agent_id_to_obs: True
  bc_alpha: 2.5
