system_name: maddpg+cql
seed: 42
wandb_project: og-marl
training_steps: 3e5

task:
  env: mpe_omar
  scenario: simple_spread
  dataset: c

replay:
  sequence_length: 5
  sample_period: 1

system:
  linear_layer_dim: 64
  recurrent_layer_dim: 64
  discount: 0.99
  target_update_rate: 0.01
  critic_learning_rate: 1e-3
  policy_learning_rate: 1e-3
  add_agent_id_to_obs: True
  num_ood_actions: 10
  cql_weight: 2.0
  cql_sigma: 0.2
