env: smac_v2
scenario: terran_5_vs_5
dataset: Replay
wandb_project: og-marl-hydra
seed: 42
training_steps: 1e5
sequence_length: 20
sample_period: 1

learning_rate: 3e-4
linear_layer_dim: 64
recurrent_layer_dim: 64
discount: 0.99
target_update_period: 200
add_agent_id_to_obs: True